{% set name = "xpdConf" %}
{% set version = "0.4.5" %}
{% set sha256 = "63d50b8cce841eb47a45aa92376db48843a3e1db4e014eead7ad22399ce33e9f" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/xpdAcq/{{ name }}/releases/download/{{ version }}/xpdConf-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
    - setuptools
  run:
    - python
    - databroker
    - pyyaml

test:
  imports:
    - xpdconf

about:
  home: http://github.com/xpdAcq/xpdConf
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Configuration for XPD beamlines

extra:
  recipe-maintainers:
    - chiahaoliu
    - sbillinge
