travis:
  secure:
    BINSTAR_TOKEN: VUU7RxY2STUthhTHDb8aaJf6MNUrPBIMcbcSXeCBsWFGJscgBP5eKhDlKrSSmzD4FYhfvqP2xwuQPJv8QYMBnSNIjlvJrMQRhXU6CmH1CSBldpuwHYVEIwlZRM9tydOl3AWaIIOqubNhgbSnTC6xIqu9z1qjp/AZC1oGNNW++Oijaso+A1XgGY+hvBlyeZ6E2asRfF/a1sfltZ9jVXm1CYxHyCOgGZLPdK5oOUaSNoxHyaeGkFVjLrZD3CoVmeI+85gKgYJiGX9SE/MO6rdcsnuh1o4uXNI+gs/LiAS9PDVYoYE5ds2IZR+NE00mPA64zX3n2oqcgU1uxbrEh0JBwwVIliCy4EkLimY03bFNfA53TcePVTDKbz03dFMr4BxI6/SIqTMYuQdRldV+H7VyRNHob5mTP3OsePBWD9E/c4DwlLAGT62CwXSHu6itM5LxBXUL+EL/ghPuM+0TablPb+PZ1RB/XRPH/bV+XyM+LY5ruTSOQaMGms7Cj7LS+BJB+JVKAra12slFQf9tsjbjeuc8WCu9hDCt756rfxM3Jio/nMdFoiq1ebGRwPD7pc17JtxC3ah7FzNFaIUgdbbmAdjtgua+NHqVpp+AL7rEn4ZkATKCCEarHNRiljQGuXpz/PWGI3mK9Rw3tqtdq7h4rblwhP8Kyj7z+2CBVg4rkWY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
